export { getMiddleCFrequency } from './lib/getMiddleCFrequency';
export { mapData } from './lib/container/mapData';
export { mapRange } from './lib/container/mapRange';
export { mapValue } from './lib/container/mapValue';
export { noteNameOffsets } from './lib/noteNameOffsets';
export { noteNameToFrequency } from './lib/noteNameToFrequency';
export { toMidi } from './lib/toMidi';
export {
  chord,
  notes,
  accidentalToLetter,
  accidentalToSymbol,
  areEqual,
  areIntervals,
  areNotes,
  createChord,
  createMelody,
  createScale,
  flatToSharp,
  getAccidental,
  getChromaticCPosition,
  getDominant,
  getIntervals,
  getLeadingTone,
  getMediant,
  getNote,
  getNoteOnDegree,
  getOctave,
  getRoot,
  getSubdominant,
  getSubmediant,
  getSupertonic,
  getTonic,
  hasAccidental,
  hasAccidentalLetter,
  hasAccidentalSymbol,
  hasIntervalAmount,
  hasOctave,
  haveSameOctave,
  isAnhemitonic,
  isAscending,
  isCohemitonic,
  isDescending,
  isDiatonic,
  isFifth,
  isFlat,
  isHemitonic,
  isHeptatonic,
  isHexatonic,
  isMode,
  isNatural,
  isNote,
  isOctatonic,
  isOctave,
  isPentatonic,
  isScale,
  isSemitone,
  isSharp,
  isTone,
  isTriad,
  normalize,
  noteToFrequency,
  noteToMidi,
  noteToNoteDescription,
  noteDescriptionToNote,
  sharpToFlat,
  transferAccidental,
  transferStyle,
  transpose,
} from './lib/musicFns';

export {
  Scale,
  algerian,
  altered,
  arabic,
  augmented,
  balinese,
  blues,
  byzantine,
  chinese,
  chromatic,
  doubleHarmonic,
  enigmatic,
  gypsyMajor,
  harmonicMinor,
  hirajoshi,
  inSen,
  japanese,
  majorPentatonic,
  major,
  melodicMinor,
  minorPentatonic,
  mongolian,
  naturalMinor,
  pelog,
  prometheus,
  wholeTone,
  yo,
} from './lib/scales';

export {
  Interval,
  root,
  R,
  semitone,
  S,
  tone,
  T,
  tritone,
  TT,
  octave,
  O,
  perfectUnison,
  P1,
  minorSecond,
  m2,
  majorSecond,
  M2,
  minorThird,
  m3,
  majorThird,
  M3,
  perfectFourth,
  P4,
  perfectFifth,
  P5,
  minorSixth,
  m6,
  majorSixth,
  M6,
  minorSeventh,
  m7,
  majorSeventh,
  M7,
  perfectOctave,
  P8,
  diminishedSecond,
  d2,
  augmentedUnison,
  A1,
  diminishedThird,
  d3,
  augmentedSecond,
  A2,
  diminishedFourth,
  d4,
  augmentedThird,
  A3,
  diminishedFifth,
  d5,
  augmentedFourth,
  A4,
  diminishedSixth,
  d6,
  augmentedFifth,
  A5,
  diminishedSeventh,
  d7,
  augmentedSixth,
  A6,
  diminishedEighth,
  d8,
  diminishedOctave,
  augmentedSeventh,
  A7,
} from './lib/intervals';

export {
  Mode,
  ionian,
  dorian,
  phrygian,
  lydian,
  mixolydian,
  aeolian,
  locrian,
} from './lib/modes';
